# Generated by Django 3.0.6 on 2020-06-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('std', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Forth', 'Forth')], max_length=100, null=True)),
                ('fees', models.BooleanField(default=False)),
                ('partial_fee', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_fee', models.IntegerField(null=True)),
                ('fee_recieved', models.IntegerField(default=0, null=True)),
                ('one_time_fee', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
